<?php

namespace Poznet\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscribersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersRepository extends EntityRepository
{

	public function oldandnotconfirmed() {
    	$week=new \DateTime('now - 7 days');
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT S  
                         FROM PoznetNewsletterBundle:Subscribers S 
                         WHERE S.confirmed=false
                         AND S.registerDate<:week
                        
                         ')
                ->setParameter('week', $week);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    // wybiera userów  z datą  rejestracji < teraz  (juz zerejstrownych)
    public function readytosend($data) {        
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT S  
                         FROM PoznetNewsletterBundle:Subscribers S 
                         WHERE S.confirmed=true
                         AND S.registerDate<:data
                        
                         ')
                ->setParameter('data', $data);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
