<?php

namespace Poznet\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LetterRepository extends EntityRepository
{
	public function tosend() {
    	
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT L
                         FROM PoznetNewsletterBundle:Letter L 
                         WHERE L.sended=true
                         ORDER BY L.date ASC
                        
                         ');

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
