<?php

namespace Poznet\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendsRepository extends EntityRepository
{
	public function confirmsend($letter,$user) {
    	
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT count(S.id)  
                         FROM PoznetNewsletterBundle:Sends S 
                         WHERE S.letter=:letter
                         AND S.subscriber=:user
                        
                         ')
                ->setParameter('letter', $letter)
                ->setParameter('user', $user);

        try {
            $wynik = $query->getSingleScalarResult();
            if($wynik>0) return true;
            return false;

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
